// Bu dosya üretilir: python3 scripts/generate-string-symbol-shim.py
// Xcode'un `LocalizedStringResource` sembollerinin elle derlenen test betikleri için karşılığı.
import Foundation

extension LocalizedStringResource {
    static var ageRangeLabelEighteenToTwentyFour: LocalizedStringResource { LocalizedStringResource("ageRange.label.eighteenToTwentyFour") }
    static var ageRangeLabelFiftyFivePlus: LocalizedStringResource { LocalizedStringResource("ageRange.label.fiftyFivePlus") }
    static var ageRangeLabelFortyFiveToFiftyFour: LocalizedStringResource { LocalizedStringResource("ageRange.label.fortyFiveToFiftyFour") }
    static var ageRangeLabelThirtyFiveToFortyFour: LocalizedStringResource { LocalizedStringResource("ageRange.label.thirtyFiveToFortyFour") }
    static var ageRangeLabelTwentyFiveToThirtyFour: LocalizedStringResource { LocalizedStringResource("ageRange.label.twentyFiveToThirtyFour") }
    static var ageRangeLabelUndisclosed: LocalizedStringResource { LocalizedStringResource("ageRange.label.undisclosed") }
    static var appLockBody: LocalizedStringResource { LocalizedStringResource("appLock.body") }
    static var appLockReason: LocalizedStringResource { LocalizedStringResource("appLock.reason") }
    static var appLockTitle: LocalizedStringResource { LocalizedStringResource("appLock.title") }
    static var appLockUnlock: LocalizedStringResource { LocalizedStringResource("appLock.unlock") }
    static var authApple: LocalizedStringResource { LocalizedStringResource("auth.apple") }
    static var authFailed: LocalizedStringResource { LocalizedStringResource("auth.failed") }
    static var authGoogle: LocalizedStringResource { LocalizedStringResource("auth.google") }
    static var authIdentityAlreadyLinked: LocalizedStringResource { LocalizedStringResource("auth.identityAlreadyLinked") }
    static var authLinkBody: LocalizedStringResource { LocalizedStringResource("auth.linkBody") }
    static var authLinkTitle: LocalizedStringResource { LocalizedStringResource("auth.linkTitle") }
    static var authNoSavedPath: LocalizedStringResource { LocalizedStringResource("auth.noSavedPath") }
    static var authNotNow: LocalizedStringResource { LocalizedStringResource("auth.notNow") }
    static var authReturningBody: LocalizedStringResource { LocalizedStringResource("auth.returningBody") }
    static var authReturningLink: LocalizedStringResource { LocalizedStringResource("auth.returningLink") }
    static var authReturningTitle: LocalizedStringResource { LocalizedStringResource("auth.returningTitle") }
    static var authSessionMissing: LocalizedStringResource { LocalizedStringResource("auth.sessionMissing") }
    static var authSkipLink: LocalizedStringResource { LocalizedStringResource("auth.skipLink") }
    static var authWorking: LocalizedStringResource { LocalizedStringResource("auth.working") }
    static var blockLibraryBodyGroundingCue1: LocalizedStringResource { LocalizedStringResource("blockLibrary.bodyGrounding.cue1") }
    static var blockLibraryBodyGroundingCue2: LocalizedStringResource { LocalizedStringResource("blockLibrary.bodyGrounding.cue2") }
    static var blockLibraryBodyGroundingCue3: LocalizedStringResource { LocalizedStringResource("blockLibrary.bodyGrounding.cue3") }
    static var blockLibraryBodyGroundingCue4: LocalizedStringResource { LocalizedStringResource("blockLibrary.bodyGrounding.cue4") }
    static var blockLibraryBodyGroundingTitle: LocalizedStringResource { LocalizedStringResource("blockLibrary.bodyGrounding.title") }
    static var blockLibraryBreathAwarenessCue1: LocalizedStringResource { LocalizedStringResource("blockLibrary.breathAwareness.cue1") }
    static var blockLibraryBreathAwarenessCue2: LocalizedStringResource { LocalizedStringResource("blockLibrary.breathAwareness.cue2") }
    static var blockLibraryBreathAwarenessCue3: LocalizedStringResource { LocalizedStringResource("blockLibrary.breathAwareness.cue3") }
    static var blockLibraryBreathAwarenessCue4: LocalizedStringResource { LocalizedStringResource("blockLibrary.breathAwareness.cue4") }
    static var blockLibraryBreathAwarenessTitle: LocalizedStringResource { LocalizedStringResource("blockLibrary.breathAwareness.title") }
    static var blockLibraryReflectionNoticeCue1: LocalizedStringResource { LocalizedStringResource("blockLibrary.reflectionNotice.cue1") }
    static var blockLibraryReflectionNoticeCue2: LocalizedStringResource { LocalizedStringResource("blockLibrary.reflectionNotice.cue2") }
    static var blockLibraryReflectionNoticeCue3: LocalizedStringResource { LocalizedStringResource("blockLibrary.reflectionNotice.cue3") }
    static var blockLibraryReflectionNoticeTitle: LocalizedStringResource { LocalizedStringResource("blockLibrary.reflectionNotice.title") }
    static var buttonCancel: LocalizedStringResource { LocalizedStringResource("button.cancel") }
    static var buttonDoneKeyboard: LocalizedStringResource { LocalizedStringResource("button.doneKeyboard") }
    static var buttonFinish: LocalizedStringResource { LocalizedStringResource("button.finish") }
    static var buttonNext: LocalizedStringResource { LocalizedStringResource("button.next") }
    static var buttonResume: LocalizedStringResource { LocalizedStringResource("button.resume") }
    static var buttonRetry: LocalizedStringResource { LocalizedStringResource("button.retry") }
    static var buttonSave: LocalizedStringResource { LocalizedStringResource("button.save") }
    static var buttonSkip: LocalizedStringResource { LocalizedStringResource("button.skip") }
    static var buttonSkipQuestion: LocalizedStringResource { LocalizedStringResource("button.skipQuestion") }
    static var buttonStart: LocalizedStringResource { LocalizedStringResource("button.start") }
    static var buttonUnderstood: LocalizedStringResource { LocalizedStringResource("button.understood") }
    static var clinicalDisclaimer: LocalizedStringResource { LocalizedStringResource("clinicalDisclaimer") }
    static func commitmentBody(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("commitment.body") }
    static var commitmentClearSignature: LocalizedStringResource { LocalizedStringResource("commitment.clearSignature") }
    static var commitmentContinueTransition: LocalizedStringResource { LocalizedStringResource("commitment.continueTransition") }
    static var commitmentDayOneTransition: LocalizedStringResource { LocalizedStringResource("commitment.dayOneTransition") }
    static var commitmentDrawHint: LocalizedStringResource { LocalizedStringResource("commitment.drawHint") }
    static var commitmentHeadline: LocalizedStringResource { LocalizedStringResource("commitment.headline") }
    static var commitmentHoldToContinue: LocalizedStringResource { LocalizedStringResource("commitment.holdToContinue") }
    static var commitmentHoldToStart: LocalizedStringResource { LocalizedStringResource("commitment.holdToStart") }
    static var commitmentLeadAvoidance: LocalizedStringResource { LocalizedStringResource("commitment.leadAvoidance") }
    static var commitmentLeadProblem: LocalizedStringResource { LocalizedStringResource("commitment.leadProblem") }
    static var commitmentSaveError: LocalizedStringResource { LocalizedStringResource("commitment.saveError") }
    static var commitmentSimpleMark: LocalizedStringResource { LocalizedStringResource("commitment.simpleMark") }
    static var commonBack: LocalizedStringResource { LocalizedStringResource("common.back") }
    static func commonPercent(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("common.percent") }
    static var commonProgress: LocalizedStringResource { LocalizedStringResource("common.progress") }
    static var crisisBody: LocalizedStringResource { LocalizedStringResource("crisis.body") }
    static var crisisHeadline: LocalizedStringResource { LocalizedStringResource("crisis.headline") }
    static var discoverAllDone: LocalizedStringResource { LocalizedStringResource("discover.allDone") }
    static var discoverAllDoneBody: LocalizedStringResource { LocalizedStringResource("discover.allDoneBody") }
    static var discoverAudioPreparing: LocalizedStringResource { LocalizedStringResource("discover.audioPreparing") }
    static var discoverAudioUnavailable: LocalizedStringResource { LocalizedStringResource("discover.audioUnavailable") }
    static var discoverBackToPath: LocalizedStringResource { LocalizedStringResource("discover.backToPath") }
    static var discoverCancel: LocalizedStringResource { LocalizedStringResource("discover.cancel") }
    static var discoverCatalogError: LocalizedStringResource { LocalizedStringResource("discover.catalogError") }
    static var discoverClose: LocalizedStringResource { LocalizedStringResource("discover.close") }
    static var discoverCollapseHint: LocalizedStringResource { LocalizedStringResource("discover.collapseHint") }
    static var discoverCollectionNote: LocalizedStringResource { LocalizedStringResource("discover.collectionNote") }
    static var discoverComingSoon: LocalizedStringResource { LocalizedStringResource("discover.comingSoon") }
    static var discoverCompleted: LocalizedStringResource { LocalizedStringResource("discover.completed") }
    static var discoverCompletedBody: LocalizedStringResource { LocalizedStringResource("discover.completedBody") }
    static var discoverContinuePath: LocalizedStringResource { LocalizedStringResource("discover.continuePath") }
    static var discoverContinuing: LocalizedStringResource { LocalizedStringResource("discover.continuing") }
    static var discoverDone: LocalizedStringResource { LocalizedStringResource("discover.done") }
    static var discoverDuration: LocalizedStringResource { LocalizedStringResource("discover.duration") }
    static var discoverExpandHint: LocalizedStringResource { LocalizedStringResource("discover.expandHint") }
    static var discoverHeaderTitle: LocalizedStringResource { LocalizedStringResource("discover.headerTitle") }
    static var discoverJoin: LocalizedStringResource { LocalizedStringResource("discover.join") }
    static var discoverJoinBody: LocalizedStringResource { LocalizedStringResource("discover.joinBody") }
    static var discoverJoinTitle: LocalizedStringResource { LocalizedStringResource("discover.joinTitle") }
    static var discoverLoading: LocalizedStringResource { LocalizedStringResource("discover.loading") }
    static var discoverNextLocked: LocalizedStringResource { LocalizedStringResource("discover.nextLocked") }
    static var discoverNow: LocalizedStringResource { LocalizedStringResource("discover.now") }
    static var discoverOffline: LocalizedStringResource { LocalizedStringResource("discover.offline") }
    static var discoverPause: LocalizedStringResource { LocalizedStringResource("discover.pause") }
    static var discoverPersonalAction: LocalizedStringResource { LocalizedStringResource("discover.personalAction") }
    static var discoverPersonalBody: LocalizedStringResource { LocalizedStringResource("discover.personalBody") }
    static var discoverPreview: LocalizedStringResource { LocalizedStringResource("discover.preview") }
    static var discoverPreviewNote: LocalizedStringResource { LocalizedStringResource("discover.previewNote") }
    static func discoverProgress(_ arg1: Int, _ arg2: Int) -> LocalizedStringResource { LocalizedStringResource("discover.progress") }
    static var discoverQuiet: LocalizedStringResource { LocalizedStringResource("discover.quiet") }
    static var discoverReady: LocalizedStringResource { LocalizedStringResource("discover.ready") }
    static var discoverReplay: LocalizedStringResource { LocalizedStringResource("discover.replay") }
    static var discoverResume: LocalizedStringResource { LocalizedStringResource("discover.resume") }
    static var discoverRetry: LocalizedStringResource { LocalizedStringResource("discover.retry") }
    static var discoverSaveError: LocalizedStringResource { LocalizedStringResource("discover.saveError") }
    static var discoverSectionAttention: LocalizedStringResource { LocalizedStringResource("discover.section.attention") }
    static var discoverSectionRelief: LocalizedStringResource { LocalizedStringResource("discover.section.relief") }
    static var discoverSectionRest: LocalizedStringResource { LocalizedStringResource("discover.section.rest") }
    static var discoverSectionToSelf: LocalizedStringResource { LocalizedStringResource("discover.section.toSelf") }
    static var discoverStart: LocalizedStringResource { LocalizedStringResource("discover.start") }
    static func discoverStepNumber(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("discover.stepNumber") }
    static var discoverSteps: LocalizedStringResource { LocalizedStringResource("discover.steps") }
    static var emptyCheckPath: LocalizedStringResource { LocalizedStringResource("empty.checkPath") }
    static var emptyDiscoverBody: LocalizedStringResource { LocalizedStringResource("empty.discoverBody") }
    static var emptyDiscoverHeadline: LocalizedStringResource { LocalizedStringResource("empty.discoverHeadline") }
    static var emptyNoBadges: LocalizedStringResource { LocalizedStringResource("empty.noBadges") }
    static var emptyNoMeasurements: LocalizedStringResource { LocalizedStringResource("empty.noMeasurements") }
    static var emptyNoPath: LocalizedStringResource { LocalizedStringResource("empty.noPath") }
    static var emptyNoSavedSessions: LocalizedStringResource { LocalizedStringResource("empty.noSavedSessions") }
    static var emptyNoSearchResults: LocalizedStringResource { LocalizedStringResource("empty.noSearchResults") }
    static var emptyPathInvitation: LocalizedStringResource { LocalizedStringResource("empty.pathInvitation") }
    static var emptyPathInvitationBody: LocalizedStringResource { LocalizedStringResource("empty.pathInvitationBody") }
    static var emptyPathInvitationNote: LocalizedStringResource { LocalizedStringResource("empty.pathInvitationNote") }
    static var emptyReturnToPath: LocalizedStringResource { LocalizedStringResource("empty.returnToPath") }
    static var errorAudioFailed: LocalizedStringResource { LocalizedStringResource("error.audioFailed") }
    static var errorOffline: LocalizedStringResource { LocalizedStringResource("error.offline") }
    static var errorPathGenerationFailed: LocalizedStringResource { LocalizedStringResource("error.pathGenerationFailed") }
    static var errorPaymentFailed: LocalizedStringResource { LocalizedStringResource("error.paymentFailed") }
    static var errorServer: LocalizedStringResource { LocalizedStringResource("error.server") }
    static var genderLabelMan: LocalizedStringResource { LocalizedStringResource("gender.label.man") }
    static var genderLabelOther: LocalizedStringResource { LocalizedStringResource("gender.label.other") }
    static var genderLabelUndisclosed: LocalizedStringResource { LocalizedStringResource("gender.label.undisclosed") }
    static var genderLabelWoman: LocalizedStringResource { LocalizedStringResource("gender.label.woman") }
    static var intensityScaleAccessibility: LocalizedStringResource { LocalizedStringResource("intensityScale.accessibility") }
    static var intensityScaleHigh: LocalizedStringResource { LocalizedStringResource("intensityScale.high") }
    static var intensityScaleLow: LocalizedStringResource { LocalizedStringResource("intensityScale.low") }
    static var intensityScaleNotSelected: LocalizedStringResource { LocalizedStringResource("intensityScale.notSelected") }
    static var loadingDiscover: LocalizedStringResource { LocalizedStringResource("loading.discover") }
    static var loadingSteps1: LocalizedStringResource { LocalizedStringResource("loading.steps.1") }
    static var loadingSteps2: LocalizedStringResource { LocalizedStringResource("loading.steps.2") }
    static var loadingSteps3: LocalizedStringResource { LocalizedStringResource("loading.steps.3") }
    static var loadingSteps4: LocalizedStringResource { LocalizedStringResource("loading.steps.4") }
    static var meAnonymousBody: LocalizedStringResource { LocalizedStringResource("me.anonymousBody") }
    static var meAnonymousTitle: LocalizedStringResource { LocalizedStringResource("me.anonymousTitle") }
    static var meBadgeEarnedFirstStep: LocalizedStringResource { LocalizedStringResource("me.badge.earned.firstStep") }
    static var meBadgeEarnedMeasureDay14: LocalizedStringResource { LocalizedStringResource("me.badge.earned.measureDay14") }
    static var meBadgeEarnedMeasureDay7: LocalizedStringResource { LocalizedStringResource("me.badge.earned.measureDay7") }
    static var meBadgeEarnedNote10: LocalizedStringResource { LocalizedStringResource("me.badge.earned.note10") }
    static var meBadgeEarnedNoteFirst: LocalizedStringResource { LocalizedStringResource("me.badge.earned.noteFirst") }
    static var meBadgeEarnedPathComplete: LocalizedStringResource { LocalizedStringResource("me.badge.earned.pathComplete") }
    static var meBadgeEarnedPhaseAwareness: LocalizedStringResource { LocalizedStringResource("me.badge.earned.phaseAwareness") }
    static var meBadgeEarnedPhaseBehavior: LocalizedStringResource { LocalizedStringResource("me.badge.earned.phaseBehavior") }
    static var meBadgeEarnedPhaseClosing: LocalizedStringResource { LocalizedStringResource("me.badge.earned.phaseClosing") }
    static var meBadgeEarnedPhaseRelief: LocalizedStringResource { LocalizedStringResource("me.badge.earned.phaseRelief") }
    static var meBadgeEarnedPhaseSkill: LocalizedStringResource { LocalizedStringResource("me.badge.earned.phaseSkill") }
    static var meBadgeEarnedWeek3: LocalizedStringResource { LocalizedStringResource("me.badge.earned.week3") }
    static var meBadgeEarnedWeek5: LocalizedStringResource { LocalizedStringResource("me.badge.earned.week5") }
    static var meBadgeEarnedWeek7: LocalizedStringResource { LocalizedStringResource("me.badge.earned.week7") }
    static var meBadgeFamilyJournal: LocalizedStringResource { LocalizedStringResource("me.badge.family.journal") }
    static var meBadgeFamilyMeasurement: LocalizedStringResource { LocalizedStringResource("me.badge.family.measurement") }
    static var meBadgeFamilyPath: LocalizedStringResource { LocalizedStringResource("me.badge.family.path") }
    static var meBadgeFamilyStreak: LocalizedStringResource { LocalizedStringResource("me.badge.family.streak") }
    static var meBadgeHowToEarnFirstStep: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.firstStep") }
    static var meBadgeHowToEarnMeasureDay14: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.measureDay14") }
    static var meBadgeHowToEarnMeasureDay7: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.measureDay7") }
    static var meBadgeHowToEarnNote10: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.note10") }
    static var meBadgeHowToEarnNoteFirst: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.noteFirst") }
    static var meBadgeHowToEarnPathComplete: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.pathComplete") }
    static var meBadgeHowToEarnPhaseAwareness: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.phaseAwareness") }
    static var meBadgeHowToEarnPhaseBehavior: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.phaseBehavior") }
    static var meBadgeHowToEarnPhaseClosing: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.phaseClosing") }
    static var meBadgeHowToEarnPhaseRelief: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.phaseRelief") }
    static var meBadgeHowToEarnPhaseSkill: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.phaseSkill") }
    static var meBadgeHowToEarnWeek3: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.week3") }
    static var meBadgeHowToEarnWeek5: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.week5") }
    static var meBadgeHowToEarnWeek7: LocalizedStringResource { LocalizedStringResource("me.badge.howToEarn.week7") }
    static var meBadgeTitleFirstStep: LocalizedStringResource { LocalizedStringResource("me.badge.title.firstStep") }
    static var meBadgeTitleMeasureDay14: LocalizedStringResource { LocalizedStringResource("me.badge.title.measureDay14") }
    static var meBadgeTitleMeasureDay7: LocalizedStringResource { LocalizedStringResource("me.badge.title.measureDay7") }
    static var meBadgeTitleNote10: LocalizedStringResource { LocalizedStringResource("me.badge.title.note10") }
    static var meBadgeTitleNoteFirst: LocalizedStringResource { LocalizedStringResource("me.badge.title.noteFirst") }
    static var meBadgeTitlePathComplete: LocalizedStringResource { LocalizedStringResource("me.badge.title.pathComplete") }
    static var meBadgeTitlePhaseAwareness: LocalizedStringResource { LocalizedStringResource("me.badge.title.phaseAwareness") }
    static var meBadgeTitlePhaseBehavior: LocalizedStringResource { LocalizedStringResource("me.badge.title.phaseBehavior") }
    static var meBadgeTitlePhaseClosing: LocalizedStringResource { LocalizedStringResource("me.badge.title.phaseClosing") }
    static var meBadgeTitlePhaseRelief: LocalizedStringResource { LocalizedStringResource("me.badge.title.phaseRelief") }
    static var meBadgeTitlePhaseSkill: LocalizedStringResource { LocalizedStringResource("me.badge.title.phaseSkill") }
    static var meBadgeTitleWeek3: LocalizedStringResource { LocalizedStringResource("me.badge.title.week3") }
    static var meBadgeTitleWeek5: LocalizedStringResource { LocalizedStringResource("me.badge.title.week5") }
    static var meBadgeTitleWeek7: LocalizedStringResource { LocalizedStringResource("me.badge.title.week7") }
    static func meBadgeAccessibility(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.badgeAccessibility") }
    static func meBadgeAccessibilityEarned(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.badgeAccessibilityEarned") }
    static var meBadgeLockedLabel: LocalizedStringResource { LocalizedStringResource("me.badgeLockedLabel") }
    static var meBadgesAll: LocalizedStringResource { LocalizedStringResource("me.badgesAll") }
    static var meBadgesFirstHint: LocalizedStringResource { LocalizedStringResource("me.badgesFirstHint") }
    static var meBadgesTitle: LocalizedStringResource { LocalizedStringResource("me.badgesTitle") }
    static func meBaselineLegendCompared(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.baselineLegendCompared") }
    static func meBaselineLegendPending(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.baselineLegendPending") }
    static var meBaselineProvisional: LocalizedStringResource { LocalizedStringResource("me.baselineProvisional") }
    static var meChangeOpenHint: LocalizedStringResource { LocalizedStringResource("me.changeOpenHint") }
    static func meChangePending(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.changePending") }
    static var meChangeTitle: LocalizedStringResource { LocalizedStringResource("me.changeTitle") }
    static var meChartBaseline: LocalizedStringResource { LocalizedStringResource("me.chartBaseline") }
    static var meChartBaselinePoint: LocalizedStringResource { LocalizedStringResource("me.chartBaselinePoint") }
    static var meChartBetterBehavior: LocalizedStringResource { LocalizedStringResource("me.chartBetter.behavior") }
    static var meChartBetterEmotion: LocalizedStringResource { LocalizedStringResource("me.chartBetter.emotion") }
    static var meChartBetterSelfEfficacy: LocalizedStringResource { LocalizedStringResource("me.chartBetter.selfEfficacy") }
    static var meChartWorseBehavior: LocalizedStringResource { LocalizedStringResource("me.chartWorse.behavior") }
    static var meChartWorseEmotion: LocalizedStringResource { LocalizedStringResource("me.chartWorse.emotion") }
    static var meChartWorseSelfEfficacy: LocalizedStringResource { LocalizedStringResource("me.chartWorse.selfEfficacy") }
    static var meChartXAxis: LocalizedStringResource { LocalizedStringResource("me.chartXAxis") }
    static var meChartYAxis: LocalizedStringResource { LocalizedStringResource("me.chartYAxis") }
    static var meContinuePathCTA: LocalizedStringResource { LocalizedStringResource("me.continuePathCTA") }
    static func meContinuePathCaption(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.continuePathCaption") }
    static func meContinuePathCardLabel(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.continuePathCardLabel") }
    static func meContinuePathProgress(_ arg1: Int, _ arg2: Int) -> LocalizedStringResource { LocalizedStringResource("me.continuePathProgress") }
    static var meContinuePathTitle: LocalizedStringResource { LocalizedStringResource("me.continuePathTitle") }
    static var meDirectionWordBehaviorImproved: LocalizedStringResource { LocalizedStringResource("me.directionWord.behavior.improved") }
    static var meDirectionWordBehaviorWorsened: LocalizedStringResource { LocalizedStringResource("me.directionWord.behavior.worsened") }
    static var meDirectionWordEmotionImproved: LocalizedStringResource { LocalizedStringResource("me.directionWord.emotion.improved") }
    static var meDirectionWordEmotionWorsened: LocalizedStringResource { LocalizedStringResource("me.directionWord.emotion.worsened") }
    static var meDirectionWordSelfEfficacyImproved: LocalizedStringResource { LocalizedStringResource("me.directionWord.selfEfficacy.improved") }
    static var meDirectionWordSelfEfficacyWorsened: LocalizedStringResource { LocalizedStringResource("me.directionWord.selfEfficacy.worsened") }
    static var meDirectionWordUnchanged: LocalizedStringResource { LocalizedStringResource("me.directionWord.unchanged") }
    static var meFragmentBehaviorImprovedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.behavior.improved.false") }
    static var meFragmentBehaviorImprovedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.behavior.improved.true") }
    static var meFragmentBehaviorUnchangedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.behavior.unchanged.false") }
    static var meFragmentBehaviorUnchangedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.behavior.unchanged.true") }
    static var meFragmentBehaviorWorsened: LocalizedStringResource { LocalizedStringResource("me.fragment.behavior.worsened") }
    static var meFragmentEmotionImprovedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.emotion.improved.false") }
    static var meFragmentEmotionImprovedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.emotion.improved.true") }
    static var meFragmentEmotionUnchangedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.emotion.unchanged.false") }
    static var meFragmentEmotionUnchangedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.emotion.unchanged.true") }
    static var meFragmentEmotionWorsened: LocalizedStringResource { LocalizedStringResource("me.fragment.emotion.worsened") }
    static var meFragmentSelfEfficacyImprovedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.selfEfficacy.improved.false") }
    static var meFragmentSelfEfficacyImprovedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.selfEfficacy.improved.true") }
    static var meFragmentSelfEfficacyUnchangedFalse: LocalizedStringResource { LocalizedStringResource("me.fragment.selfEfficacy.unchanged.false") }
    static var meFragmentSelfEfficacyUnchangedTrue: LocalizedStringResource { LocalizedStringResource("me.fragment.selfEfficacy.unchanged.true") }
    static var meFragmentSelfEfficacyWorsened: LocalizedStringResource { LocalizedStringResource("me.fragment.selfEfficacy.worsened") }
    static var meHowWeMeasure: LocalizedStringResource { LocalizedStringResource("me.howWeMeasure") }
    static func meJournalAfterStep(_ arg1: Int, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.journalAfterStep") }
    static var meJournalAll: LocalizedStringResource { LocalizedStringResource("me.journalAll") }
    static func meJournalAvoidance(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.journalAvoidance") }
    static var meJournalCardInvite: LocalizedStringResource { LocalizedStringResource("me.journalCardInvite") }
    static var meJournalCardLabel: LocalizedStringResource { LocalizedStringResource("me.journalCardLabel") }
    static var meJournalCardOpenHint: LocalizedStringResource { LocalizedStringResource("me.journalCardOpenHint") }
    static var meJournalCardWrite: LocalizedStringResource { LocalizedStringResource("me.journalCardWrite") }
    static var meJournalDelete: LocalizedStringResource { LocalizedStringResource("me.journalDelete") }
    static var meJournalDeleteBody: LocalizedStringResource { LocalizedStringResource("me.journalDeleteBody") }
    static var meJournalDeleteFailed: LocalizedStringResource { LocalizedStringResource("me.journalDeleteFailed") }
    static var meJournalDeleteOriginBody: LocalizedStringResource { LocalizedStringResource("me.journalDeleteOriginBody") }
    static var meJournalDeleteTitle: LocalizedStringResource { LocalizedStringResource("me.journalDeleteTitle") }
    static var meJournalEdit: LocalizedStringResource { LocalizedStringResource("me.journalEdit") }
    static var meJournalEditNote: LocalizedStringResource { LocalizedStringResource("me.journalEditNote") }
    static var meJournalEmpty: LocalizedStringResource { LocalizedStringResource("me.journalEmpty") }
    static var meJournalHidden: LocalizedStringResource { LocalizedStringResource("me.journalHidden") }
    static var meJournalNewNote: LocalizedStringResource { LocalizedStringResource("me.journalNewNote") }
    static func meJournalNoteCaption(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.journalNoteCaption") }
    static func meJournalOrigin(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.journalOrigin") }
    static var meJournalOwnNote: LocalizedStringResource { LocalizedStringResource("me.journalOwnNote") }
    static func meJournalQuestion(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.journalQuestion") }
    static var meJournalTitle: LocalizedStringResource { LocalizedStringResource("me.journalTitle") }
    static var meLastWeek: LocalizedStringResource { LocalizedStringResource("me.lastWeek") }
    static func meLayerAccessibility(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.layerAccessibility") }
    static var meLayerPickerLabel: LocalizedStringResource { LocalizedStringResource("me.layerPickerLabel") }
    static var meLayerShortBehavior: LocalizedStringResource { LocalizedStringResource("me.layerShort.behavior") }
    static var meLayerShortEmotion: LocalizedStringResource { LocalizedStringResource("me.layerShort.emotion") }
    static var meLayerShortSelfEfficacy: LocalizedStringResource { LocalizedStringResource("me.layerShort.selfEfficacy") }
    static var meLeastChanged: LocalizedStringResource { LocalizedStringResource("me.leastChanged") }
    static var meLinkAccount: LocalizedStringResource { LocalizedStringResource("me.linkAccount") }
    static var meMethodBehavior: LocalizedStringResource { LocalizedStringResource("me.method.behavior") }
    static var meMethodClinical: LocalizedStringResource { LocalizedStringResource("me.method.clinical") }
    static var meMethodClinicalTitle: LocalizedStringResource { LocalizedStringResource("me.method.clinicalTitle") }
    static var meMethodEmotion: LocalizedStringResource { LocalizedStringResource("me.method.emotion") }
    static var meMethodIntro: LocalizedStringResource { LocalizedStringResource("me.method.intro") }
    static var meMethodLayersTitle: LocalizedStringResource { LocalizedStringResource("me.method.layersTitle") }
    static var meMethodRotation: LocalizedStringResource { LocalizedStringResource("me.method.rotation") }
    static var meMethodRotationTitle: LocalizedStringResource { LocalizedStringResource("me.method.rotationTitle") }
    static var meMethodSelfEfficacy: LocalizedStringResource { LocalizedStringResource("me.method.selfEfficacy") }
    static var meMethodTitle: LocalizedStringResource { LocalizedStringResource("me.method.title") }
    static var meMostChanged: LocalizedStringResource { LocalizedStringResource("me.mostChanged") }
    static var meNoActivePath: LocalizedStringResource { LocalizedStringResource("me.noActivePath") }
    static var meNoteLimitReached: LocalizedStringResource { LocalizedStringResource("me.noteLimitReached") }
    static var meNotePlaceholder: LocalizedStringResource { LocalizedStringResource("me.notePlaceholder") }
    static func meNoteRemaining(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.noteRemaining") }
    static var meNoteSaveFailed: LocalizedStringResource { LocalizedStringResource("me.noteSaveFailed") }
    static var meOfflineHeader: LocalizedStringResource { LocalizedStringResource("me.offlineHeader") }
    static var meOpenSettings: LocalizedStringResource { LocalizedStringResource("me.openSettings") }
    static func mePathActive(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.pathActive") }
    static var mePathClearProgress: LocalizedStringResource { LocalizedStringResource("me.pathClearProgress") }
    static var mePathCompleted: LocalizedStringResource { LocalizedStringResource("me.pathCompleted") }
    static func mePathDateRange(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.pathDateRange") }
    static func mePathDays(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.pathDays") }
    static var mePathFinishedHeader: LocalizedStringResource { LocalizedStringResource("me.pathFinishedHeader") }
    static var mePathJournalTitle: LocalizedStringResource { LocalizedStringResource("me.pathJournalTitle") }
    static var mePathJustStarted: LocalizedStringResource { LocalizedStringResource("me.pathJustStarted") }
    static var mePathPartialProgress: LocalizedStringResource { LocalizedStringResource("me.pathPartialProgress") }
    static func mePathSteps(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.pathSteps") }
    static func mePathStopped(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.pathStopped") }
    static var mePathStoppedDetail: LocalizedStringResource { LocalizedStringResource("me.pathStoppedDetail") }
    static var mePathsTitle: LocalizedStringResource { LocalizedStringResource("me.pathsTitle") }
    static var mePhotoAccessibility: LocalizedStringResource { LocalizedStringResource("me.photoAccessibility") }
    static var mePhotoChoose: LocalizedStringResource { LocalizedStringResource("me.photoChoose") }
    static var mePhotoFailed: LocalizedStringResource { LocalizedStringResource("me.photoFailed") }
    static var mePhotoRemove: LocalizedStringResource { LocalizedStringResource("me.photoRemove") }
    static var mePhotoTitle: LocalizedStringResource { LocalizedStringResource("me.photoTitle") }
    static var mePointBaseline: LocalizedStringResource { LocalizedStringResource("me.pointBaseline") }
    static var mePointFinal: LocalizedStringResource { LocalizedStringResource("me.pointFinal") }
    static func mePointStep(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.pointStep") }
    static var mePreferencesFootnote: LocalizedStringResource { LocalizedStringResource("me.preferencesFootnote") }
    static var mePreferencesTitle: LocalizedStringResource { LocalizedStringResource("me.preferencesTitle") }
    static var meReminderDenied: LocalizedStringResource { LocalizedStringResource("me.reminderDenied") }
    static var meReminderLabel: LocalizedStringResource { LocalizedStringResource("me.reminderLabel") }
    static var meReminderOff: LocalizedStringResource { LocalizedStringResource("me.reminderOff") }
    static var meReminderOffValue: LocalizedStringResource { LocalizedStringResource("me.reminderOffValue") }
    static func meReminderSource(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("me.reminderSource") }
    static var meReminderTimeLabel: LocalizedStringResource { LocalizedStringResource("me.reminderTimeLabel") }
    static var meReminderToggle: LocalizedStringResource { LocalizedStringResource("me.reminderToggle") }
    static var meScreenTitle: LocalizedStringResource { LocalizedStringResource("me.screenTitle") }
    static func meSealAccessibility(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.sealAccessibility") }
    static var meSettingsAboutHeader: LocalizedStringResource { LocalizedStringResource("me.settings.aboutHeader") }
    static var meSettingsAccountHeader: LocalizedStringResource { LocalizedStringResource("me.settings.accountHeader") }
    static var meSettingsAnalytics: LocalizedStringResource { LocalizedStringResource("me.settings.analytics") }
    static var meSettingsAnalyticsFooter: LocalizedStringResource { LocalizedStringResource("me.settings.analyticsFooter") }
    static var meSettingsAppLock: LocalizedStringResource { LocalizedStringResource("me.settings.appLock") }
    static var meSettingsAppLockFooter: LocalizedStringResource { LocalizedStringResource("me.settings.appLockFooter") }
    static var meSettingsAppLockUnavailable: LocalizedStringResource { LocalizedStringResource("me.settings.appLockUnavailable") }
    static var meSettingsDataHeader: LocalizedStringResource { LocalizedStringResource("me.settings.dataHeader") }
    static var meSettingsDeleteAccount: LocalizedStringResource { LocalizedStringResource("me.settings.deleteAccount") }
    static var meSettingsDeleteAccountBody: LocalizedStringResource { LocalizedStringResource("me.settings.deleteAccountBody") }
    static var meSettingsDeleteAccountFailed: LocalizedStringResource { LocalizedStringResource("me.settings.deleteAccountFailed") }
    static var meSettingsDeleteAccountTitle: LocalizedStringResource { LocalizedStringResource("me.settings.deleteAccountTitle") }
    static var meSettingsDeleteJournal: LocalizedStringResource { LocalizedStringResource("me.settings.deleteJournal") }
    static var meSettingsDeleteJournalBody: LocalizedStringResource { LocalizedStringResource("me.settings.deleteJournalBody") }
    static var meSettingsDeleteJournalTitle: LocalizedStringResource { LocalizedStringResource("me.settings.deleteJournalTitle") }
    static var meSettingsEraseFooter: LocalizedStringResource { LocalizedStringResource("me.settings.eraseFooter") }
    static var meSettingsEraseLocal: LocalizedStringResource { LocalizedStringResource("me.settings.eraseLocal") }
    static var meSettingsEraseTitle: LocalizedStringResource { LocalizedStringResource("me.settings.eraseTitle") }
    static var meSettingsExport: LocalizedStringResource { LocalizedStringResource("me.settings.export") }
    static var meSettingsExportFooter: LocalizedStringResource { LocalizedStringResource("me.settings.exportFooter") }
    static var meSettingsExportPreview: LocalizedStringResource { LocalizedStringResource("me.settings.exportPreview") }
    static var meSettingsHideJournal: LocalizedStringResource { LocalizedStringResource("me.settings.hideJournal") }
    static var meSettingsIrreversibleHeader: LocalizedStringResource { LocalizedStringResource("me.settings.irreversibleHeader") }
    static var meSettingsLinkedNo: LocalizedStringResource { LocalizedStringResource("me.settings.linkedNo") }
    static var meSettingsLinkedRow: LocalizedStringResource { LocalizedStringResource("me.settings.linkedRow") }
    static var meSettingsLinkedYes: LocalizedStringResource { LocalizedStringResource("me.settings.linkedYes") }
    static var meSettingsNameFailed: LocalizedStringResource { LocalizedStringResource("me.settings.nameFailed") }
    static var meSettingsNameHint: LocalizedStringResource { LocalizedStringResource("me.settings.nameHint") }
    static var meSettingsNameNone: LocalizedStringResource { LocalizedStringResource("me.settings.nameNone") }
    static var meSettingsNamePlaceholder: LocalizedStringResource { LocalizedStringResource("me.settings.namePlaceholder") }
    static var meSettingsNameRow: LocalizedStringResource { LocalizedStringResource("me.settings.nameRow") }
    static var meSettingsNameTitle: LocalizedStringResource { LocalizedStringResource("me.settings.nameTitle") }
    static var meSettingsNotificationPrivacy: LocalizedStringResource { LocalizedStringResource("me.settings.notificationPrivacy") }
    static var meSettingsPrivacyHeader: LocalizedStringResource { LocalizedStringResource("me.settings.privacyHeader") }
    static var meSettingsReminderHeader: LocalizedStringResource { LocalizedStringResource("me.settings.reminderHeader") }
    static var meSettingsSignOut: LocalizedStringResource { LocalizedStringResource("me.settings.signOut") }
    static var meSettingsSignOutBody: LocalizedStringResource { LocalizedStringResource("me.settings.signOutBody") }
    static var meSettingsSignOutTitle: LocalizedStringResource { LocalizedStringResource("me.settings.signOutTitle") }
    static var meSettingsTitle: LocalizedStringResource { LocalizedStringResource("me.settings.title") }
    static var meSettingsVersionRow: LocalizedStringResource { LocalizedStringResource("me.settings.versionRow") }
    static var meSettingsButton: LocalizedStringResource { LocalizedStringResource("me.settingsButton") }
    static var meSettingsRow: LocalizedStringResource { LocalizedStringResource("me.settingsRow") }
    static func meStepPosition(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.stepPosition") }
    static var meSupportSubtitle: LocalizedStringResource { LocalizedStringResource("me.supportSubtitle") }
    static var meSupportTitle: LocalizedStringResource { LocalizedStringResource("me.supportTitle") }
    static var meThisWeek: LocalizedStringResource { LocalizedStringResource("me.thisWeek") }
    static var meToday: LocalizedStringResource { LocalizedStringResource("me.today") }
    static var meToneLabel: LocalizedStringResource { LocalizedStringResource("me.toneLabel") }
    static var meUniformChangeImproved: LocalizedStringResource { LocalizedStringResource("me.uniformChange.improved") }
    static var meUniformChangeUnchangedFalse: LocalizedStringResource { LocalizedStringResource("me.uniformChange.unchanged.false") }
    static var meUniformChangeUnchangedTrue: LocalizedStringResource { LocalizedStringResource("me.uniformChange.unchanged.true") }
    static var meUniformChangeWorsened: LocalizedStringResource { LocalizedStringResource("me.uniformChange.worsened") }
    static func meVersion(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("me.version") }
    static func meWeekDays(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("me.weekDays") }
    static var meYesterday: LocalizedStringResource { LocalizedStringResource("me.yesterday") }
    static var measurementLayerLabelBehavior: LocalizedStringResource { LocalizedStringResource("measurementLayer.label.behavior") }
    static var measurementLayerLabelEmotion: LocalizedStringResource { LocalizedStringResource("measurementLayer.label.emotion") }
    static var measurementLayerLabelSelfEfficacy: LocalizedStringResource { LocalizedStringResource("measurementLayer.label.selfEfficacy") }
    static var measurementLibraryAgreementOptions1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.agreementOptions.1") }
    static var measurementLibraryAgreementOptions2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.agreementOptions.2") }
    static var measurementLibraryAgreementOptions3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.agreementOptions.3") }
    static var measurementLibraryAgreementOptions4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.agreementOptions.4") }
    static var measurementLibraryAgreementOptions5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.agreementOptions.5") }
    static var measurementLibraryAvoidanceCount1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.avoidanceCount.1") }
    static var measurementLibraryAvoidanceCount2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.avoidanceCount.2") }
    static var measurementLibraryAvoidanceCountA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.avoidanceCount.a") }
    static var measurementLibraryAvoidanceCountB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.avoidanceCount.b") }
    static var measurementLibraryAvoidanceCountC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.avoidanceCount.c") }
    static var measurementLibraryBehaviorItemAnger1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anger.1") }
    static var measurementLibraryBehaviorItemAnger2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anger.2") }
    static var measurementLibraryBehaviorItemAnger3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anger.3") }
    static var measurementLibraryBehaviorItemAnxietySelfcritGriefUnnamed1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anxiety.selfcrit.grief.unnamed.1") }
    static var measurementLibraryBehaviorItemAnxietySelfcritGriefUnnamed2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anxiety.selfcrit.grief.unnamed.2") }
    static var measurementLibraryBehaviorItemAnxietySelfcritGriefUnnamed3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anxiety.selfcrit.grief.unnamed.3") }
    static var measurementLibraryBehaviorItemAnxietySelfcritGriefUnnamed4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anxiety.selfcrit.grief.unnamed.4") }
    static var measurementLibraryBehaviorItemAnxietySelfcritGriefUnnamed5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.anxiety.selfcrit.grief.unnamed.5") }
    static var measurementLibraryBehaviorItemBurnout1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.burnout.1") }
    static var measurementLibraryBehaviorItemBurnout2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.burnout.2") }
    static var measurementLibraryBehaviorItemBurnout3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.burnout.3") }
    static var measurementLibraryBehaviorItemBurnout4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.burnout.4") }
    static var measurementLibraryBehaviorItemBurnout5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.burnout.5") }
    static var measurementLibraryBehaviorItemExamFocus1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.exam.focus.1") }
    static var measurementLibraryBehaviorItemExamFocus2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.exam.focus.2") }
    static var measurementLibraryBehaviorItemExamFocus3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.exam.focus.3") }
    static var measurementLibraryBehaviorItemSleep1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.sleep.1") }
    static var measurementLibraryBehaviorItemSleep2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.sleep.2") }
    static var measurementLibraryBehaviorItemSleep3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.sleep.3") }
    static var measurementLibraryBehaviorItemSleep4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.sleep.4") }
    static var measurementLibraryBehaviorItemSleep5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.sleep.5") }
    static var measurementLibraryBehaviorItemSocial1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.social.1") }
    static var measurementLibraryBehaviorItemSocial2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.social.2") }
    static var measurementLibraryBehaviorItemSocial3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.social.3") }
    static var measurementLibraryBehaviorItemSocial4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.social.4") }
    static var measurementLibraryBehaviorItemSocial5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.behaviorItem.social.5") }
    static var measurementLibraryBelievesChangePossibleA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.believesChangePossible.a") }
    static var measurementLibraryBelievesChangePossibleB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.believesChangePossible.b") }
    static var measurementLibraryBelievesChangePossibleC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.believesChangePossible.c") }
    static var measurementLibraryDailyImpact1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.1") }
    static var measurementLibraryDailyImpact2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.2") }
    static var measurementLibraryDailyImpact3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.3") }
    static var measurementLibraryDailyImpact4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.4") }
    static var measurementLibraryDailyImpact5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.5") }
    static var measurementLibraryDailyImpactA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.a") }
    static var measurementLibraryDailyImpactB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.b") }
    static var measurementLibraryDailyImpactC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.dailyImpact.c") }
    static var measurementLibraryFrequency1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.1") }
    static var measurementLibraryFrequency2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.2") }
    static var measurementLibraryFrequency3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.3") }
    static var measurementLibraryFrequency4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.4") }
    static var measurementLibraryFrequency5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.5") }
    static var measurementLibraryFrequencyA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.a") }
    static var measurementLibraryFrequencyB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.b") }
    static var measurementLibraryFrequencyC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.frequency.c") }
    static var measurementLibraryIntensityA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.intensity.a") }
    static var measurementLibraryIntensityB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.intensity.b") }
    static var measurementLibraryIntensityC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.intensity.c") }
    static var measurementLibraryKnowsWhatToDoA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.knowsWhatToDo.a") }
    static var measurementLibraryKnowsWhatToDoB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.knowsWhatToDo.b") }
    static var measurementLibraryKnowsWhatToDoC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.knowsWhatToDo.c") }
    static var measurementLibraryRangeOneToTwo: LocalizedStringResource { LocalizedStringResource("measurementLibrary.rangeOneToTwo") }
    static var measurementLibraryRangeThreeToFive: LocalizedStringResource { LocalizedStringResource("measurementLibrary.rangeThreeToFive") }
    static var measurementLibrarySleepLatency1: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.1") }
    static var measurementLibrarySleepLatency2: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.2") }
    static var measurementLibrarySleepLatency3: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.3") }
    static var measurementLibrarySleepLatency4: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.4") }
    static var measurementLibrarySleepLatency5: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.5") }
    static var measurementLibrarySleepLatencyA: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.a") }
    static var measurementLibrarySleepLatencyB: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.b") }
    static var measurementLibrarySleepLatencyC: LocalizedStringResource { LocalizedStringResource("measurementLibrary.sleepLatency.c") }
    static var moodLevelLabelCalm: LocalizedStringResource { LocalizedStringResource("moodLevel.label.calm") }
    static var moodLevelLabelHeavy: LocalizedStringResource { LocalizedStringResource("moodLevel.label.heavy") }
    static var moodLevelLabelMiddling: LocalizedStringResource { LocalizedStringResource("moodLevel.label.middling") }
    static var moodLevelLabelOkay: LocalizedStringResource { LocalizedStringResource("moodLevel.label.okay") }
    static var moodLevelLabelVeryHeavy: LocalizedStringResource { LocalizedStringResource("moodLevel.label.veryHeavy") }
    static var notificationDailyStep: LocalizedStringResource { LocalizedStringResource("notification.dailyStep") }
    static var notificationMicroOffer: LocalizedStringResource { LocalizedStringResource("notification.microOffer") }
    static var notificationMissedFewDays: LocalizedStringResource { LocalizedStringResource("notification.missedFewDays") }
    static var notificationMissedOneDay: LocalizedStringResource { LocalizedStringResource("notification.missedOneDay") }
    static var notificationPathWaiting: LocalizedStringResource { LocalizedStringResource("notification.pathWaiting") }
    static var notificationPrimingAllow: LocalizedStringResource { LocalizedStringResource("notificationPriming.allow") }
    static func notificationPrimingHeadline(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("notificationPriming.headline") }
    static var notificationPrimingNoGuilt: LocalizedStringResource { LocalizedStringResource("notificationPriming.noGuilt") }
    static var notificationPrimingPreviewAccessibility: LocalizedStringResource { LocalizedStringResource("notificationPriming.previewAccessibility") }
    static var notificationPrimingPreviewApp: LocalizedStringResource { LocalizedStringResource("notificationPriming.previewApp") }
    static var notificationPrimingPreviewTime: LocalizedStringResource { LocalizedStringResource("notificationPriming.previewTime") }
    static var onboardingAgeHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.ageHeadline") }
    static var onboardingAttemptsHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.attemptsHeadline") }
    static var onboardingAttemptsHint: LocalizedStringResource { LocalizedStringResource("onboarding.attemptsHint") }
    static var onboardingAttemptsOtherPlaceholder: LocalizedStringResource { LocalizedStringResource("onboarding.attemptsOtherPlaceholder") }
    static var onboardingAttemptsOtherRequired: LocalizedStringResource { LocalizedStringResource("onboarding.attemptsOtherRequired") }
    static var onboardingAttemptsTherapyNote: LocalizedStringResource { LocalizedStringResource("onboarding.attemptsTherapyNote") }
    static var onboardingAvoidanceHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.avoidanceHeadline") }
    static var onboardingAvoidanceHint: LocalizedStringResource { LocalizedStringResource("onboarding.avoidanceHint") }
    static var onboardingAvoidancePlaceholder: LocalizedStringResource { LocalizedStringResource("onboarding.avoidancePlaceholder") }
    static var onboardingAvoidanceSkip: LocalizedStringResource { LocalizedStringResource("onboarding.avoidanceSkip") }
    static var onboardingCategoriesHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.categoriesHeadline") }
    static var onboardingCategoriesHint: LocalizedStringResource { LocalizedStringResource("onboarding.categoriesHint") }
    static var onboardingChooseOneCTA: LocalizedStringResource { LocalizedStringResource("onboarding.chooseOneCTA") }
    static func onboardingDayLabel1(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("onboarding.dayLabel.1") }
    static func onboardingDayLabel2(_ arg1: Int, _ arg2: Int) -> LocalizedStringResource { LocalizedStringResource("onboarding.dayLabel.2") }
    static var onboardingDurationHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.durationHeadline") }
    static var onboardingExpectationChartAccessibilityLabel: LocalizedStringResource { LocalizedStringResource("onboarding.expectationChartAccessibilityLabel") }
    static var onboardingExpectationEndCaption: LocalizedStringResource { LocalizedStringResource("onboarding.expectationEndCaption") }
    static var onboardingExpectationOtherAppsLabel: LocalizedStringResource { LocalizedStringResource("onboarding.expectationOtherAppsLabel") }
    static var onboardingExpectationPatikaLabel: LocalizedStringResource { LocalizedStringResource("onboarding.expectationPatikaLabel") }
    static var onboardingExpectationStartCaption: LocalizedStringResource { LocalizedStringResource("onboarding.expectationStartCaption") }
    static var onboardingFirstSessionBody: LocalizedStringResource { LocalizedStringResource("onboarding.firstSessionBody") }
    static var onboardingFirstSessionComplete: LocalizedStringResource { LocalizedStringResource("onboarding.firstSessionComplete") }
    static var onboardingFirstSessionHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.firstSessionHeadline") }
    static var onboardingGenderHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.genderHeadline") }
    static var onboardingGenerationHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.generationHeadline") }
    static var onboardingHonestExpectationEarlyDays: LocalizedStringResource { LocalizedStringResource("onboarding.honestExpectationEarlyDays") }
    static var onboardingHonestExpectationHeadline1: LocalizedStringResource { LocalizedStringResource("onboarding.honestExpectationHeadline.1") }
    static func onboardingHonestExpectationHeadline2(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("onboarding.honestExpectationHeadline.2") }
    static var onboardingHonestExpectationMeasurement: LocalizedStringResource { LocalizedStringResource("onboarding.honestExpectationMeasurement") }
    static var onboardingHonestExpectationTimeline: LocalizedStringResource { LocalizedStringResource("onboarding.honestExpectationTimeline") }
    static var onboardingIdentityStatsNote: LocalizedStringResource { LocalizedStringResource("onboarding.identityStatsNote") }
    static var onboardingLibraryComparisonClosing: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonClosing") }
    static var onboardingLibraryComparisonHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonHeadline") }
    static var onboardingLibraryComparisonOurs1: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonOurs.1") }
    static var onboardingLibraryComparisonOurs2: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonOurs.2") }
    static var onboardingLibraryComparisonOurs3: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonOurs.3") }
    static var onboardingLibraryComparisonOurs4: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonOurs.4") }
    static var onboardingLibraryComparisonOursTitle: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonOursTitle") }
    static var onboardingLibraryComparisonTheirs1: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonTheirs.1") }
    static var onboardingLibraryComparisonTheirs2: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonTheirs.2") }
    static var onboardingLibraryComparisonTheirs3: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonTheirs.3") }
    static var onboardingLibraryComparisonTheirs4: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonTheirs.4") }
    static var onboardingLibraryComparisonTheirsTitle: LocalizedStringResource { LocalizedStringResource("onboarding.libraryComparisonTheirsTitle") }
    static var onboardingMeasurementIntroCTA: LocalizedStringResource { LocalizedStringResource("onboarding.measurementIntroCTA") }
    static var onboardingMeasurementIntroEffort: LocalizedStringResource { LocalizedStringResource("onboarding.measurementIntroEffort") }
    static func onboardingMeasurementIntroHeadline(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("onboarding.measurementIntroHeadline") }
    static var onboardingMeasurementIntroPurpose: LocalizedStringResource { LocalizedStringResource("onboarding.measurementIntroPurpose") }
    static var onboardingMirroringAvoidanceLead: LocalizedStringResource { LocalizedStringResource("onboarding.mirroringAvoidanceLead") }
    static var onboardingMirroringClosing: LocalizedStringResource { LocalizedStringResource("onboarding.mirroringClosing") }
    static var onboardingMirroringDurationLead: LocalizedStringResource { LocalizedStringResource("onboarding.mirroringDurationLead") }
    static var onboardingMirroringDurationTail: LocalizedStringResource { LocalizedStringResource("onboarding.mirroringDurationTail") }
    static var onboardingMirroringHeadline1: LocalizedStringResource { LocalizedStringResource("onboarding.mirroringHeadline.1") }
    static func onboardingMirroringHeadline2(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("onboarding.mirroringHeadline.2") }
    static func onboardingMirroringSituation(_ arg1: String, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("onboarding.mirroringSituation") }
    static var onboardingMoodHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.moodHeadline") }
    static var onboardingMoodHint: LocalizedStringResource { LocalizedStringResource("onboarding.moodHint") }
    static var onboardingNameFirstCTA: LocalizedStringResource { LocalizedStringResource("onboarding.nameFirstCTA") }
    static var onboardingNameHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.nameHeadline") }
    static var onboardingNameHint: LocalizedStringResource { LocalizedStringResource("onboarding.nameHint") }
    static var onboardingNamePlaceholder: LocalizedStringResource { LocalizedStringResource("onboarding.namePlaceholder") }
    static var onboardingNameSkip: LocalizedStringResource { LocalizedStringResource("onboarding.nameSkip") }
    static var onboardingNotAloneHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.notAloneHeadline") }
    static var onboardingNotAloneResearchLine: LocalizedStringResource { LocalizedStringResource("onboarding.notAloneResearchLine") }
    static var onboardingPickPointCTA: LocalizedStringResource { LocalizedStringResource("onboarding.pickPointCTA") }
    static var onboardingProblemTextHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.problemTextHeadline") }
    static var onboardingProblemTextHint: LocalizedStringResource { LocalizedStringResource("onboarding.problemTextHint") }
    static var onboardingProblemTextSkip: LocalizedStringResource { LocalizedStringResource("onboarding.problemTextSkip") }
    static var onboardingReminderAccept: LocalizedStringResource { LocalizedStringResource("onboarding.reminderAccept") }
    static var onboardingReminderChange: LocalizedStringResource { LocalizedStringResource("onboarding.reminderChange") }
    static func onboardingReminderHeadline(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("onboarding.reminderHeadline") }
    static var onboardingReminderPickerLabel: LocalizedStringResource { LocalizedStringResource("onboarding.reminderPickerLabel") }
    static var onboardingRoadmapContinue: LocalizedStringResource { LocalizedStringResource("onboarding.roadmapContinue") }
    static var onboardingRoadmapFirstMeasurement: LocalizedStringResource { LocalizedStringResource("onboarding.roadmapFirstMeasurement") }
    static var onboardingRoadmapHeadline1: LocalizedStringResource { LocalizedStringResource("onboarding.roadmapHeadline.1") }
    static func onboardingRoadmapHeadline2(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("onboarding.roadmapHeadline.2") }
    static var onboardingRoadmapMeasurement: LocalizedStringResource { LocalizedStringResource("onboarding.roadmapMeasurement") }
    static var onboardingRoadmapMeasurementDescription: LocalizedStringResource { LocalizedStringResource("onboarding.roadmapMeasurementDescription") }
    static func onboardingRoadmapMeta(_ arg1: Int, _ arg2: Int) -> LocalizedStringResource { LocalizedStringResource("onboarding.roadmapMeta") }
    static var onboardingStepNotWritten: LocalizedStringResource { LocalizedStringResource("onboarding.stepNotWritten") }
    static var onboardingTimingHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.timingHeadline") }
    static var onboardingTimingHint: LocalizedStringResource { LocalizedStringResource("onboarding.timingHint") }
    static var onboardingToneHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.toneHeadline") }
    static var onboardingToneHint: LocalizedStringResource { LocalizedStringResource("onboarding.toneHint") }
    static var onboardingWelcomeBody: LocalizedStringResource { LocalizedStringResource("onboarding.welcomeBody") }
    static var onboardingWelcomeCTA: LocalizedStringResource { LocalizedStringResource("onboarding.welcomeCTA") }
    static var onboardingWelcomeHeadline: LocalizedStringResource { LocalizedStringResource("onboarding.welcomeHeadline") }
    static var pathCollapseDetails: LocalizedStringResource { LocalizedStringResource("path.collapseDetails") }
    static var pathCompletedNote: LocalizedStringResource { LocalizedStringResource("path.completedNote") }
    static var pathContinueCTA: LocalizedStringResource { LocalizedStringResource("path.continueCTA") }
    static var pathCurrentLocation: LocalizedStringResource { LocalizedStringResource("path.currentLocation") }
    static var pathDetailsCollapsed: LocalizedStringResource { LocalizedStringResource("path.detailsCollapsed") }
    static var pathDetailsExpanded: LocalizedStringResource { LocalizedStringResource("path.detailsExpanded") }
    static var pathDoneCTA: LocalizedStringResource { LocalizedStringResource("path.doneCTA") }
    static var pathExpandDetails: LocalizedStringResource { LocalizedStringResource("path.expandDetails") }
    static var pathFinishedBody: LocalizedStringResource { LocalizedStringResource("path.finishedBody") }
    static var pathFinishedHeadline: LocalizedStringResource { LocalizedStringResource("path.finishedHeadline") }
    static var pathLoadError: LocalizedStringResource { LocalizedStringResource("path.loadError") }
    static var pathLoading: LocalizedStringResource { LocalizedStringResource("path.loading") }
    static var pathLockedAccessibility: LocalizedStringResource { LocalizedStringResource("path.lockedAccessibility") }
    static var pathLockedHint: LocalizedStringResource { LocalizedStringResource("path.lockedHint") }
    static var pathMeasurementNote: LocalizedStringResource { LocalizedStringResource("path.measurementNote") }
    static var pathMeasurementNotice: LocalizedStringResource { LocalizedStringResource("path.measurementNotice") }
    static var pathReadyNote: LocalizedStringResource { LocalizedStringResource("path.readyNote") }
    static var pathReplayCTA: LocalizedStringResource { LocalizedStringResource("path.replayCTA") }
    static var pathRetry: LocalizedStringResource { LocalizedStringResource("path.retry") }
    static var pathScreenTitle: LocalizedStringResource { LocalizedStringResource("path.screenTitle") }
    static var pathStartCTA: LocalizedStringResource { LocalizedStringResource("path.startCTA") }
    static func pathStepLabel(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("path.stepLabel") }
    static var pathMeasurementCompletionError: LocalizedStringResource { LocalizedStringResource("pathMeasurement.completionError") }
    static var pathMeasurementIntroBody: LocalizedStringResource { LocalizedStringResource("pathMeasurement.introBody") }
    static var pathMeasurementIntroCTA: LocalizedStringResource { LocalizedStringResource("pathMeasurement.introCTA") }
    static func pathMeasurementIntroHeadline(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("pathMeasurement.introHeadline") }
    static var pathMeasurementSaveError: LocalizedStringResource { LocalizedStringResource("pathMeasurement.saveError") }
    static var pathPhaseLabelAwareness: LocalizedStringResource { LocalizedStringResource("pathPhase.label.awareness") }
    static var pathPhaseLabelBehavior: LocalizedStringResource { LocalizedStringResource("pathPhase.label.behavior") }
    static var pathPhaseLabelClosing: LocalizedStringResource { LocalizedStringResource("pathPhase.label.closing") }
    static var pathPhaseLabelRelief: LocalizedStringResource { LocalizedStringResource("pathPhase.label.relief") }
    static var pathPhaseLabelSkill: LocalizedStringResource { LocalizedStringResource("pathPhase.label.skill") }
    static var pathPhaseRoadmapDescriptionAwareness: LocalizedStringResource { LocalizedStringResource("pathPhase.roadmapDescription.awareness") }
    static var pathPhaseRoadmapDescriptionBehavior: LocalizedStringResource { LocalizedStringResource("pathPhase.roadmapDescription.behavior") }
    static var pathPhaseRoadmapDescriptionClosing: LocalizedStringResource { LocalizedStringResource("pathPhase.roadmapDescription.closing") }
    static var pathPhaseRoadmapDescriptionRelief: LocalizedStringResource { LocalizedStringResource("pathPhase.roadmapDescription.relief") }
    static var pathPhaseRoadmapDescriptionSkill: LocalizedStringResource { LocalizedStringResource("pathPhase.roadmapDescription.skill") }
    static func paywallBody(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("paywall.body") }
    static var paywallCheckAgain: LocalizedStringResource { LocalizedStringResource("paywall.checkAgain") }
    static var paywallChecking: LocalizedStringResource { LocalizedStringResource("paywall.checking") }
    static var paywallContinue: LocalizedStringResource { LocalizedStringResource("paywall.continue") }
    static var paywallHeadline: LocalizedStringResource { LocalizedStringResource("paywall.headline") }
    static var paywallNotNow: LocalizedStringResource { LocalizedStringResource("paywall.notNow") }
    static var paywallOnePayment: LocalizedStringResource { LocalizedStringResource("paywall.onePayment") }
    static var paywallPurchaseError: LocalizedStringResource { LocalizedStringResource("paywall.purchaseError") }
    static var paywallRestore: LocalizedStringResource { LocalizedStringResource("paywall.restore") }
    static var paywallRestoreUnavailable: LocalizedStringResource { LocalizedStringResource("paywall.restoreUnavailable") }
    static var paywallUnavailable: LocalizedStringResource { LocalizedStringResource("paywall.unavailable") }
    static var paywallViewOffer: LocalizedStringResource { LocalizedStringResource("paywall.viewOffer") }
    static var previousAttemptLabelBreathing: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.breathing") }
    static var previousAttemptLabelNothing: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.nothing") }
    static var previousAttemptLabelOther: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.other") }
    static var previousAttemptLabelOtherApps: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.otherApps") }
    static var previousAttemptLabelTherapyOngoing: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.therapyOngoing") }
    static var previousAttemptLabelTherapyPast: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.therapyPast") }
    static var previousAttemptLabelYoutube: LocalizedStringResource { LocalizedStringResource("previousAttempt.label.youtube") }
    static var priceDecision: LocalizedStringResource { LocalizedStringResource("price.decision") }
    static var priceFree: LocalizedStringResource { LocalizedStringResource("price.free") }
    static var priceHeadline: LocalizedStringResource { LocalizedStringResource("price.headline") }
    static var priceOptionMonthly: LocalizedStringResource { LocalizedStringResource("price.option.monthly") }
    static var priceOptionMonthlyPrice: LocalizedStringResource { LocalizedStringResource("price.option.monthly.price") }
    static var priceOptionSingle: LocalizedStringResource { LocalizedStringResource("price.option.single") }
    static var priceOptionSinglePrice: LocalizedStringResource { LocalizedStringResource("price.option.single.price") }
    static var priceOptionYearly: LocalizedStringResource { LocalizedStringResource("price.option.yearly") }
    static var priceOptionYearlyPrice: LocalizedStringResource { LocalizedStringResource("price.option.yearly.price") }
    static var priceOptionsHeader: LocalizedStringResource { LocalizedStringResource("price.optionsHeader") }
    static var pricePromise: LocalizedStringResource { LocalizedStringResource("price.promise") }
    static var problemCategoryCommonalityLineAnger: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.anger") }
    static var problemCategoryCommonalityLineAnxiety: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.anxiety") }
    static var problemCategoryCommonalityLineBurnout: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.burnout") }
    static var problemCategoryCommonalityLineExam: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.exam") }
    static var problemCategoryCommonalityLineFocus: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.focus") }
    static var problemCategoryCommonalityLineGrief: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.grief") }
    static var problemCategoryCommonalityLineSelfcrit: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.selfcrit") }
    static var problemCategoryCommonalityLineSleep: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.sleep") }
    static var problemCategoryCommonalityLineSocial: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.social") }
    static var problemCategoryCommonalityLineUnnamed: LocalizedStringResource { LocalizedStringResource("problemCategory.commonalityLine.unnamed") }
    static var problemCategoryLabelAnger: LocalizedStringResource { LocalizedStringResource("problemCategory.label.anger") }
    static var problemCategoryLabelAnxiety: LocalizedStringResource { LocalizedStringResource("problemCategory.label.anxiety") }
    static var problemCategoryLabelBurnout: LocalizedStringResource { LocalizedStringResource("problemCategory.label.burnout") }
    static var problemCategoryLabelExam: LocalizedStringResource { LocalizedStringResource("problemCategory.label.exam") }
    static var problemCategoryLabelFocus: LocalizedStringResource { LocalizedStringResource("problemCategory.label.focus") }
    static var problemCategoryLabelGrief: LocalizedStringResource { LocalizedStringResource("problemCategory.label.grief") }
    static var problemCategoryLabelSelfcrit: LocalizedStringResource { LocalizedStringResource("problemCategory.label.selfcrit") }
    static var problemCategoryLabelSleep: LocalizedStringResource { LocalizedStringResource("problemCategory.label.sleep") }
    static var problemCategoryLabelSocial: LocalizedStringResource { LocalizedStringResource("problemCategory.label.social") }
    static var problemCategoryLabelUnnamed: LocalizedStringResource { LocalizedStringResource("problemCategory.label.unnamed") }
    static var problemCategoryMirrorPhraseAnger: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.anger") }
    static var problemCategoryMirrorPhraseAnxiety: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.anxiety") }
    static var problemCategoryMirrorPhraseBurnout: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.burnout") }
    static var problemCategoryMirrorPhraseExam: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.exam") }
    static var problemCategoryMirrorPhraseFocus: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.focus") }
    static var problemCategoryMirrorPhraseGrief: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.grief") }
    static var problemCategoryMirrorPhraseSelfcrit: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.selfcrit") }
    static var problemCategoryMirrorPhraseSleep: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.sleep") }
    static var problemCategoryMirrorPhraseSocial: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.social") }
    static var problemCategoryMirrorPhraseUnnamed: LocalizedStringResource { LocalizedStringResource("problemCategory.mirrorPhrase.unnamed") }
    static var problemCategoryProvisionalPathTitleAnger: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.anger") }
    static var problemCategoryProvisionalPathTitleAnxiety: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.anxiety") }
    static var problemCategoryProvisionalPathTitleBurnout: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.burnout") }
    static var problemCategoryProvisionalPathTitleExam: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.exam") }
    static var problemCategoryProvisionalPathTitleFocus: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.focus") }
    static var problemCategoryProvisionalPathTitleGrief: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.grief") }
    static var problemCategoryProvisionalPathTitleSelfcrit: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.selfcrit") }
    static var problemCategoryProvisionalPathTitleSleep: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.sleep") }
    static var problemCategoryProvisionalPathTitleSocial: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.social") }
    static var problemCategoryProvisionalPathTitleUnnamed: LocalizedStringResource { LocalizedStringResource("problemCategory.provisionalPathTitle.unnamed") }
    static var problemCategoryTextPlaceholderAnger: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.anger") }
    static var problemCategoryTextPlaceholderAnxiety: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.anxiety") }
    static var problemCategoryTextPlaceholderBurnout: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.burnout") }
    static var problemCategoryTextPlaceholderExam: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.exam") }
    static var problemCategoryTextPlaceholderFocus: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.focus") }
    static var problemCategoryTextPlaceholderGrief: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.grief") }
    static var problemCategoryTextPlaceholderSelfcrit: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.selfcrit") }
    static var problemCategoryTextPlaceholderSleep: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.sleep") }
    static var problemCategoryTextPlaceholderSocial: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.social") }
    static var problemCategoryTextPlaceholderUnnamed: LocalizedStringResource { LocalizedStringResource("problemCategory.textPlaceholder.unnamed") }
    static var problemDurationLabelFewDays: LocalizedStringResource { LocalizedStringResource("problemDuration.label.fewDays") }
    static var problemDurationLabelFewWeeks: LocalizedStringResource { LocalizedStringResource("problemDuration.label.fewWeeks") }
    static var problemDurationLabelMonths: LocalizedStringResource { LocalizedStringResource("problemDuration.label.months") }
    static var problemDurationLabelUnsure: LocalizedStringResource { LocalizedStringResource("problemDuration.label.unsure") }
    static var problemDurationLabelYears: LocalizedStringResource { LocalizedStringResource("problemDuration.label.years") }
    static var problemDurationMirrorPhraseFewDays: LocalizedStringResource { LocalizedStringResource("problemDuration.mirrorPhrase.fewDays") }
    static var problemDurationMirrorPhraseFewWeeks: LocalizedStringResource { LocalizedStringResource("problemDuration.mirrorPhrase.fewWeeks") }
    static var problemDurationMirrorPhraseMonths: LocalizedStringResource { LocalizedStringResource("problemDuration.mirrorPhrase.months") }
    static var problemDurationMirrorPhraseYears: LocalizedStringResource { LocalizedStringResource("problemDuration.mirrorPhrase.years") }
    static var problemTimingLabelBedtime: LocalizedStringResource { LocalizedStringResource("problemTiming.label.bedtime") }
    static var problemTimingLabelDaytime: LocalizedStringResource { LocalizedStringResource("problemTiming.label.daytime") }
    static var problemTimingLabelEvening: LocalizedStringResource { LocalizedStringResource("problemTiming.label.evening") }
    static var problemTimingLabelMorning: LocalizedStringResource { LocalizedStringResource("problemTiming.label.morning") }
    static var problemTimingLabelNoPattern: LocalizedStringResource { LocalizedStringResource("problemTiming.label.noPattern") }
    static var problemTimingMirrorPhraseBedtime: LocalizedStringResource { LocalizedStringResource("problemTiming.mirrorPhrase.bedtime") }
    static var problemTimingMirrorPhraseDaytime: LocalizedStringResource { LocalizedStringResource("problemTiming.mirrorPhrase.daytime") }
    static var problemTimingMirrorPhraseEvening: LocalizedStringResource { LocalizedStringResource("problemTiming.mirrorPhrase.evening") }
    static var problemTimingMirrorPhraseMorning: LocalizedStringResource { LocalizedStringResource("problemTiming.mirrorPhrase.morning") }
    static var problemTimingMirrorPhraseNoPattern: LocalizedStringResource { LocalizedStringResource("problemTiming.mirrorPhrase.noPattern") }
    static var problemTimingReminderReasonBedtime: LocalizedStringResource { LocalizedStringResource("problemTiming.reminderReason.bedtime") }
    static var problemTimingReminderReasonDaytime: LocalizedStringResource { LocalizedStringResource("problemTiming.reminderReason.daytime") }
    static var problemTimingReminderReasonEvening: LocalizedStringResource { LocalizedStringResource("problemTiming.reminderReason.evening") }
    static var problemTimingReminderReasonMorning: LocalizedStringResource { LocalizedStringResource("problemTiming.reminderReason.morning") }
    static var problemTimingReminderReasonNoPattern: LocalizedStringResource { LocalizedStringResource("problemTiming.reminderReason.noPattern") }
    static var reminderDialAccessibility: LocalizedStringResource { LocalizedStringResource("reminderDial.accessibility") }
    static var reminderDialAccessibilityHint: LocalizedStringResource { LocalizedStringResource("reminderDial.accessibilityHint") }
    static var reminderFrequencyLabelDaily: LocalizedStringResource { LocalizedStringResource("reminderFrequency.label.daily") }
    static var reminderFrequencyLabelNever: LocalizedStringResource { LocalizedStringResource("reminderFrequency.label.never") }
    static var reminderFrequencyLabelOnlyWhenMissed: LocalizedStringResource { LocalizedStringResource("reminderFrequency.label.onlyWhenMissed") }
    static var reminderFrequencyLabelWeekly: LocalizedStringResource { LocalizedStringResource("reminderFrequency.label.weekly") }
    static var returningAfterBreak: LocalizedStringResource { LocalizedStringResource("returning.afterBreak") }
    static var returningAfterLongBreak: LocalizedStringResource { LocalizedStringResource("returning.afterLongBreak") }
    static var sessionAudioPreparing: LocalizedStringResource { LocalizedStringResource("session.audioPreparing") }
    static func sessionCompletedBody(_ arg1: Int) -> LocalizedStringResource { LocalizedStringResource("session.completedBody") }
    static var sessionCompletedCTA: LocalizedStringResource { LocalizedStringResource("session.completedCTA") }
    static var sessionCompletedHeadline: LocalizedStringResource { LocalizedStringResource("session.completedHeadline") }
    static var sessionFallbackClosing: LocalizedStringResource { LocalizedStringResource("session.fallbackClosing") }
    static var sessionFallbackOpening: LocalizedStringResource { LocalizedStringResource("session.fallbackOpening") }
    static var sessionFallbackStepTitle: LocalizedStringResource { LocalizedStringResource("session.fallbackStepTitle") }
    static var sessionLeave: LocalizedStringResource { LocalizedStringResource("session.leave") }
    static func sessionLeftEarlyBody(_ arg1: String) -> LocalizedStringResource { LocalizedStringResource("session.leftEarlyBody") }
    static var sessionLeftEarlyHeadline: LocalizedStringResource { LocalizedStringResource("session.leftEarlyHeadline") }
    static var sessionOwnWordsFraming: LocalizedStringResource { LocalizedStringResource("session.ownWordsFraming") }
    static var sessionPause: LocalizedStringResource { LocalizedStringResource("session.pause") }
    static var sessionPausedNote: LocalizedStringResource { LocalizedStringResource("session.pausedNote") }
    static var sessionPreparing: LocalizedStringResource { LocalizedStringResource("session.preparing") }
    static var sessionReflectionError: LocalizedStringResource { LocalizedStringResource("session.reflectionError") }
    static var sessionReflectionHint: LocalizedStringResource { LocalizedStringResource("session.reflectionHint") }
    static var sessionReflectionPlaceholder: LocalizedStringResource { LocalizedStringResource("session.reflectionPlaceholder") }
    static var sessionReflectionSave: LocalizedStringResource { LocalizedStringResource("session.reflectionSave") }
    static var sessionReflectionSkip: LocalizedStringResource { LocalizedStringResource("session.reflectionSkip") }
    static var sessionResume: LocalizedStringResource { LocalizedStringResource("session.resume") }
    static var sessionSkipBackward: LocalizedStringResource { LocalizedStringResource("session.skipBackward") }
    static var sessionSkipForward: LocalizedStringResource { LocalizedStringResource("session.skipForward") }
    static func sessionStepEyebrow(_ arg1: Int, _ arg2: String) -> LocalizedStringResource { LocalizedStringResource("session.stepEyebrow") }
    static var sessionFeedbackLabelCouldNotFocus: LocalizedStringResource { LocalizedStringResource("sessionFeedback.label.couldNotFocus") }
    static var sessionFeedbackLabelHelped: LocalizedStringResource { LocalizedStringResource("sessionFeedback.label.helped") }
    static var sessionFeedbackLabelStruggled: LocalizedStringResource { LocalizedStringResource("sessionFeedback.label.struggled") }
    static var supportAuLifelineName: LocalizedStringResource { LocalizedStringResource("support.au.lifeline.name") }
    static var supportBody: LocalizedStringResource { LocalizedStringResource("support.body") }
    static var supportBrCvvName: LocalizedStringResource { LocalizedStringResource("support.br.cvv.name") }
    static var supportCa988Name: LocalizedStringResource { LocalizedStringResource("support.ca.988.name") }
    static var supportCall: LocalizedStringResource { LocalizedStringResource("support.call") }
    static var supportChDargeboteneHandName: LocalizedStringResource { LocalizedStringResource("support.ch.dargeboteneHand.name") }
    static var supportClose: LocalizedStringResource { LocalizedStringResource("support.close") }
    static var supportDeTelefonSeelsorgeDetail: LocalizedStringResource { LocalizedStringResource("support.de.telefonSeelsorge.detail") }
    static var supportDeTelefonSeelsorgeName: LocalizedStringResource { LocalizedStringResource("support.de.telefonSeelsorge.name") }
    static var supportDetailCrisisLine: LocalizedStringResource { LocalizedStringResource("support.detail.crisisLine") }
    static var supportDetailMentalHealthLine: LocalizedStringResource { LocalizedStringResource("support.detail.mentalHealthLine") }
    static var supportDirectory: LocalizedStringResource { LocalizedStringResource("support.directory") }
    static var supportDkLivslinienName: LocalizedStringResource { LocalizedStringResource("support.dk.livslinien.name") }
    static var supportEmergencyDetail: LocalizedStringResource { LocalizedStringResource("support.emergency.detail") }
    static var supportEmergencyName: LocalizedStringResource { LocalizedStringResource("support.emergency.name") }
    static var supportEs024Name: LocalizedStringResource { LocalizedStringResource("support.es.024.name") }
    static var supportFiMieliName: LocalizedStringResource { LocalizedStringResource("support.fi.mieli.name") }
    static var supportFr3114Name: LocalizedStringResource { LocalizedStringResource("support.fr.3114.name") }
    static var supportGbSamaritansDetail: LocalizedStringResource { LocalizedStringResource("support.gb.samaritans.detail") }
    static var supportGbSamaritansName: LocalizedStringResource { LocalizedStringResource("support.gb.samaritans.name") }
    static var supportInTeleManasName: LocalizedStringResource { LocalizedStringResource("support.in.teleManas.name") }
    static var supportItTelefonoAmicoName: LocalizedStringResource { LocalizedStringResource("support.it.telefonoAmico.name") }
    static var supportJpYorisoiName: LocalizedStringResource { LocalizedStringResource("support.jp.yorisoi.name") }
    static var supportMxLineaVidaName: LocalizedStringResource { LocalizedStringResource("support.mx.lineaVida.name") }
    static var supportNl113Name: LocalizedStringResource { LocalizedStringResource("support.nl.113.name") }
    static var supportNoKirkensSosName: LocalizedStringResource { LocalizedStringResource("support.no.kirkensSos.name") }
    static var supportNotEmergencyService: LocalizedStringResource { LocalizedStringResource("support.notEmergencyService") }
    static var supportNz1737Name: LocalizedStringResource { LocalizedStringResource("support.nz.1737.name") }
    static var supportSeMindName: LocalizedStringResource { LocalizedStringResource("support.se.mind.name") }
    static var supportSgSosName: LocalizedStringResource { LocalizedStringResource("support.sg.sos.name") }
    static var supportTapToCall: LocalizedStringResource { LocalizedStringResource("support.tapToCall") }
    static var supportTitle: LocalizedStringResource { LocalizedStringResource("support.title") }
    static var supportTrSocialSupportDetail: LocalizedStringResource { LocalizedStringResource("support.tr.socialSupport.detail") }
    static var supportTrSocialSupportName: LocalizedStringResource { LocalizedStringResource("support.tr.socialSupport.name") }
    static var supportUs988Detail: LocalizedStringResource { LocalizedStringResource("support.us.988.detail") }
    static var supportUs988Name: LocalizedStringResource { LocalizedStringResource("support.us.988.name") }
    static var supportZaSadagName: LocalizedStringResource { LocalizedStringResource("support.za.sadag.name") }
    static var tabDiscover: LocalizedStringResource { LocalizedStringResource("tab.discover") }
    static var tabMe: LocalizedStringResource { LocalizedStringResource("tab.me") }
    static var tabPath: LocalizedStringResource { LocalizedStringResource("tab.path") }
    static var tonePreferenceLabelCalmAndShort: LocalizedStringResource { LocalizedStringResource("tonePreference.label.calmAndShort") }
    static var tonePreferenceLabelInfoOnly: LocalizedStringResource { LocalizedStringResource("tonePreference.label.infoOnly") }
    static var tonePreferenceLabelMoreGuiding: LocalizedStringResource { LocalizedStringResource("tonePreference.label.moreGuiding") }
    static var tonePreferenceSampleCalmAndShort: LocalizedStringResource { LocalizedStringResource("tonePreference.sample.calmAndShort") }
    static var tonePreferenceSampleInfoOnly: LocalizedStringResource { LocalizedStringResource("tonePreference.sample.infoOnly") }
    static var tonePreferenceSampleMoreGuiding: LocalizedStringResource { LocalizedStringResource("tonePreference.sample.moreGuiding") }
    static var tonePreferenceSampleLabel: LocalizedStringResource { LocalizedStringResource("tonePreference.sampleLabel") }
}
